"""疑似freee のデータアクセス層（A-8 永続化: SQLite / Postgres 両対応）。

在庫 inventory_dashboard/db.py を**独立移植**したもの（各アプリは単体で動く方針=NFR-5）。
DATABASE_URL が postgres:// なら Neon 等の Postgres(psycopg3)、無ければローカル SQLite。
呼び出し側(app.py)は常に '?' プレースホルダで SQL を書き、Postgres のときだけ '%s' に変換する。

方言差の吸収ポイント:
  - プレースホルダ : '?'(SQLite) ⇄ '%s'(psycopg)              … _Connection.execute
  - 採番          : lastrowid(SQLite) ⇄ INSERT ... RETURNING id … insert_returning_id
  - DDL          : AUTOINCREMENT / REAL ⇄ IDENTITY / DOUBLE PRECISION … *_SCHEMA_SQL
  - created_at    : 両方言とも **TEXT** に統一。疑似freee は stdlib の json.dumps で API 応答を
                    作るため、Postgres の timestamp 型(datetime)を返すと壊れる。Postgres は
                    to_char(now(),'YYYY-MM-DD HH24:MI:SS') で SQLite と同形式の文字列にする。
  - 重複無視      : INSERT ... ON CONFLICT DO NOTHING（SQLite/Postgres 双方で動く＝app.py側で統一）

秘密情報（DATABASE_URL）は環境変数のみ。コード/ログには残さない。
"""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Any, Iterator, Sequence

# 業務ロジックの型注釈に使うエイリアス。実体は _Connection（SQLite/psycopg 両対応の薄いラッパ）。
Connection = Any


def database_url() -> str:
    """接続先 URL（前後空白除去・'#' 始まりは未設定扱い＝auth/storage と同じ防御）。"""
    value = os.environ.get("DATABASE_URL", "").strip()
    if value.startswith("#"):
        return ""
    return value


def is_postgres() -> bool:
    return database_url().startswith("postgres")


# --- スキーマ DDL（方言別。CREATE TABLE IF NOT EXISTS で冪等） --------------------
# SQLite 版＝従来の SCHEMA_SQL 相当（PRAGMA + tables）。
SQLITE_SCHEMA_SQL = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS pseudo_freee_deals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    queue_id INTEGER,
    source_app TEXT NOT NULL DEFAULT 'inventory_dashboard',
    source_type TEXT NOT NULL CHECK (source_type IN ('purchase', 'sale', 'manual_expense')),
    source_id INTEGER,
    deal_type TEXT NOT NULL CHECK (deal_type IN ('expense', 'income')),
    issue_date TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    partner_name TEXT NOT NULL DEFAULT '',
    partner_master_id INTEGER,
    freee_partner_id TEXT NOT NULL DEFAULT '',
    invoice_no TEXT NOT NULL DEFAULT '',
    account_item_name TEXT NOT NULL DEFAULT '',
    tax_category TEXT NOT NULL DEFAULT '',
    amount REAL NOT NULL DEFAULT 0,
    memo TEXT NOT NULL DEFAULT '',
    payment_method TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(queue_id, source_type, source_id)
);

CREATE TABLE IF NOT EXISTS pseudo_freee_deal_lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id INTEGER NOT NULL REFERENCES pseudo_freee_deals(id) ON DELETE CASCADE,
    sku TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    quantity REAL NOT NULL DEFAULT 0,
    unit_price REAL NOT NULL DEFAULT 0,
    tax_rate REAL NOT NULL DEFAULT 0,
    tax_category TEXT NOT NULL DEFAULT '',
    amount REAL NOT NULL DEFAULT 0,
    account_item_name TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_pseudo_freee_deals_created_at ON pseudo_freee_deals(created_at);
CREATE INDEX IF NOT EXISTS idx_pseudo_freee_deals_issue_date ON pseudo_freee_deals(issue_date);

CREATE TABLE IF NOT EXISTS pseudo_freee_payees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payee_name TEXT NOT NULL UNIQUE,
    search_key TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pseudo_freee_account_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_item_name TEXT NOT NULL UNIQUE,
    default_tax_category TEXT NOT NULL DEFAULT '課税仕入 10%',
    search_key TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pseudo_freee_tax_categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tax_category TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pseudo_freee_vouchers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id INTEGER REFERENCES pseudo_freee_deals(id),
    file_name TEXT NOT NULL DEFAULT '',
    storage_path TEXT NOT NULL DEFAULT '',
    mime_type TEXT NOT NULL DEFAULT '',
    content_hash TEXT NOT NULL DEFAULT '',
    ai_extracted_json TEXT NOT NULL DEFAULT '{}',
    user_corrected_json TEXT NOT NULL DEFAULT '',
    confidence REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pseudo_freee_vouchers_created_at ON pseudo_freee_vouchers(created_at);
"""

# Postgres 版＝AUTOINCREMENT→IDENTITY / REAL→DOUBLE PRECISION / created_at は TEXT(to_char)。
POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS pseudo_freee_deals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id INTEGER,
    source_app TEXT NOT NULL DEFAULT 'inventory_dashboard',
    source_type TEXT NOT NULL CHECK (source_type IN ('purchase', 'sale', 'manual_expense')),
    source_id INTEGER,
    deal_type TEXT NOT NULL CHECK (deal_type IN ('expense', 'income')),
    issue_date TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    partner_name TEXT NOT NULL DEFAULT '',
    partner_master_id INTEGER,
    freee_partner_id TEXT NOT NULL DEFAULT '',
    invoice_no TEXT NOT NULL DEFAULT '',
    account_item_name TEXT NOT NULL DEFAULT '',
    tax_category TEXT NOT NULL DEFAULT '',
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    memo TEXT NOT NULL DEFAULT '',
    payment_method TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE(queue_id, source_type, source_id)
);

CREATE TABLE IF NOT EXISTS pseudo_freee_deal_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id INTEGER NOT NULL REFERENCES pseudo_freee_deals(id) ON DELETE CASCADE,
    sku TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_category TEXT NOT NULL DEFAULT '',
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    account_item_name TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_pseudo_freee_deals_created_at ON pseudo_freee_deals(created_at);
CREATE INDEX IF NOT EXISTS idx_pseudo_freee_deals_issue_date ON pseudo_freee_deals(issue_date);

CREATE TABLE IF NOT EXISTS pseudo_freee_payees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payee_name TEXT NOT NULL UNIQUE,
    search_key TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS pseudo_freee_account_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_item_name TEXT NOT NULL UNIQUE,
    default_tax_category TEXT NOT NULL DEFAULT '課税仕入 10%',
    search_key TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS pseudo_freee_tax_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_category TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS pseudo_freee_vouchers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_id INTEGER REFERENCES pseudo_freee_deals(id),
    file_name TEXT NOT NULL DEFAULT '',
    storage_path TEXT NOT NULL DEFAULT '',
    mime_type TEXT NOT NULL DEFAULT '',
    content_hash TEXT NOT NULL DEFAULT '',
    ai_extracted_json TEXT NOT NULL DEFAULT '{}',
    user_corrected_json TEXT NOT NULL DEFAULT '',
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_pseudo_freee_vouchers_created_at ON pseudo_freee_vouchers(created_at);
"""


def _dict_factory(cursor: sqlite3.Cursor, row: Sequence[Any]) -> dict[str, Any]:
    """SQLite の行を dict で返す（psycopg の dict_row と戻り値の形を揃える）。"""
    return {col[0]: row[idx] for idx, col in enumerate(cursor.description)}


def _to_pg_sql(sql: str) -> str:
    """'?' プレースホルダの SQL を psycopg(%s) 用に変換する（パラメータ有り専用）。

    リテラル % を先に %% へエスケープし、その後 '?' を '%s' に変える（順序が重要）。
    """
    return sql.replace("%", "%%").replace("?", "%s")


class _Connection:
    """SQLite / psycopg を同じ API で扱う薄いラッパ。

    - execute(sql, params): SQL は常に '?' で書き、Postgres のときだけ '%s' へ変換する。
      params が None のときはパラメータ無しで実行する（psycopg が SQL 内の '%' を
      プレースホルダと誤認しないようにするため）。
    - 戻り値は dict を返すカーソル（fetchone()/fetchall()/lastrowid を持つ）。
    """

    def __init__(self, raw: Any, postgres: bool) -> None:
        self._raw = raw
        self.postgres = postgres

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        if self.postgres:
            cur = self._raw.cursor()
            if params is None:
                cur.execute(sql.replace("?", "%s"))
            else:
                cur.execute(_to_pg_sql(sql), params)
            return cur
        if params is None:
            return self._raw.execute(sql)
        return self._raw.execute(sql, params)

    def executemany(self, sql: str, seq_of_params: Sequence[Sequence[Any]]) -> Any:
        if self.postgres:
            cur = self._raw.cursor()
            cur.executemany(_to_pg_sql(sql), list(seq_of_params))
            return cur
        return self._raw.executemany(sql, seq_of_params)

    def executescript(self, sql: str) -> None:
        # 複数文（スキーマDDL）をまとめて実行する。どちらの方言もパラメータ無し。
        if self.postgres:
            self._raw.cursor().execute(sql)
        else:
            self._raw.executescript(sql)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


@contextmanager
def get_conn(sqlite_path: str | os.PathLike[str] | None = None) -> Iterator[_Connection]:
    """トランザクション境界付きの接続を返す。正常終了で commit、例外で rollback、最後に close。
    Postgres のときは sqlite_path は無視される。"""
    if is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        raw = psycopg.connect(database_url(), row_factory=dict_row)
        conn = _Connection(raw, postgres=True)
    else:
        if sqlite_path is None:
            raise ValueError("sqlite_path is required when DATABASE_URL is not a Postgres URL")
        raw = sqlite3.connect(sqlite_path)
        raw.row_factory = _dict_factory
        raw.execute("PRAGMA foreign_keys = ON")
        conn = _Connection(raw, postgres=False)

    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def create_schema(conn: _Connection) -> None:
    """方言に応じたスキーマ DDL を流す（冪等: CREATE TABLE IF NOT EXISTS）。"""
    conn.executescript(POSTGRES_SCHEMA_SQL if conn.postgres else SQLITE_SCHEMA_SQL)


# 全テーブル（FK を考慮し、参照する側→される側の順で DROP する）。テスト/使い捨てDB専用。
PSEUDO_FREEE_TABLES = (
    "pseudo_freee_vouchers",     # deals を参照
    "pseudo_freee_deal_lines",   # deals を参照
    "pseudo_freee_deals",
    "pseudo_freee_payees",
    "pseudo_freee_account_items",
    "pseudo_freee_tax_categories",
)


def reset_tables(conn: _Connection) -> None:
    """全テーブルを DROP する（テスト/テスト用ブランチ専用の破壊的操作）。
    本番DBに対しては絶対に呼ばないこと（EVOLUTION_PLAN.md「テストDBの分離」）。"""
    if conn.postgres:
        for table in PSEUDO_FREEE_TABLES:
            conn.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    else:
        for table in PSEUDO_FREEE_TABLES:
            conn.execute(f"DROP TABLE IF EXISTS {table}")


def table_exists(conn: _Connection, table: str) -> bool:
    if conn.postgres:
        row = conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = ?",
            (table,),
        ).fetchone()
        return row is not None
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    ).fetchone()
    return row is not None


def has_column(conn: _Connection, table: str, column: str) -> bool:
    """table に column が存在するか（方言差を吸収）。table/column は定数のみを渡すこと。"""
    if conn.postgres:
        row = conn.execute(
            "SELECT 1 FROM information_schema.columns WHERE table_name = ? AND column_name = ?",
            (table, column),
        ).fetchone()
        return row is not None
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(row["name"] == column for row in rows)


def insert_returning_id(conn: _Connection, sql: str, params: Sequence[Any]) -> int:
    """INSERT して採番された id を返す（lastrowid と RETURNING の差を吸収）。

    sql は末尾に RETURNING を付けない INSERT ... VALUES (...) を渡す（セミコロン不要）。
    """
    if conn.postgres:
        cur = conn.execute(sql.rstrip().rstrip(";") + " RETURNING id", params)
        return int(cur.fetchone()["id"])
    cur = conn.execute(sql, params)
    return int(cur.lastrowid)
