"""DB アクセス層（EVOLUTION_PLAN.md A-2: Neon 移行）。

このモジュールが「接続・スキーマDDL・SQL方言差の吸収」を一手に引き受ける。
業務ロジック(app.py)は方言を意識せず、常に '?' プレースホルダで SQL を書く。

DATABASE_URL による切替:
  - 未設定         → ローカル SQLite（開発・テストの既定）
  - postgresql://  → Neon などの Postgres（psycopg3）

方言差を吸収する箇所:
  - プレースホルダ : '?'(SQLite)        ⇄ '%s'(psycopg)          … _Connection.execute
  - 採番          : lastrowid(SQLite)   ⇄ INSERT ... RETURNING id … insert_returning_id
  - 月の抽出      : strftime(SQLite)    ⇄ EXTRACT(Postgres)       … month_expr
  - DDL          : AUTOINCREMENT/REAL  ⇄ IDENTITY/DOUBLE PRECISION … *_SCHEMA_SQL

設計境界（EVOLUTION_PLAN.md「データアクセス境界」）:
  DB への読み書き・スキーマ所有はサーバ側(Python)が唯一の主体。フロントは触らない。
"""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Any, Iterator, Sequence

# 業務ロジックの型注釈に使うエイリアス。実体は _Connection（SQLite/psycopg 両対応の薄いラッパ）。
Connection = Any


# ---------------------------------------------------------------------------
# バックエンド判定（DATABASE_URL を都度読むので、テストで環境変数を差し替えられる）
# ---------------------------------------------------------------------------
def database_url() -> str:
    return os.environ.get("DATABASE_URL", "").strip()


def is_postgres() -> bool:
    url = database_url()
    return url.startswith("postgres://") or url.startswith("postgresql://")


# ---------------------------------------------------------------------------
# スキーマ DDL（SQLite 版 / Postgres 版を併記）
# ---------------------------------------------------------------------------
# 2つの DDL は「同じ論理スキーマ」を表す。列を足すときは必ず両方を更新すること。
# 差分は方言のみ:
#   INTEGER PRIMARY KEY AUTOINCREMENT → INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
#   REAL                              → DOUBLE PRECISION
#   created_at/updated_at の TEXT      → TIMESTAMP（CURRENT_TIMESTAMP をそのまま代入できる）
#   PRAGMA foreign_keys = ON           → Postgres は常に FK 強制のため不要
SQLITE_SCHEMA_SQL = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    supplier_name TEXT NOT NULL DEFAULT '',
    purchase_unit_price REAL NOT NULL DEFAULT 0,
    sales_unit_price REAL NOT NULL DEFAULT 0,
    tax_rate REAL NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '課税仕入/課税売上 10%',
    lead_time_days INTEGER NOT NULL DEFAULT 7,
    safety_stock INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 0,
    min_order_quantity INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS business_partners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    partner_type TEXT NOT NULL CHECK (partner_type IN ('supplier', 'customer')),
    partner_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(partner_type, partner_name)
);

CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    received_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price REAL NOT NULL CHECK (unit_price >= 0),
    tax_rate REAL NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price REAL NOT NULL CHECK (unit_price >= 0),
    tax_rate REAL NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER NOT NULL REFERENCES products(id),
    movement_type TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    movement_date TEXT NOT NULL,
    quantity_delta INTEGER NOT NULL,
    unit_price REAL NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS freee_sync_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    payload_json TEXT NOT NULL,
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_type, source_id)
);

CREATE TABLE IF NOT EXISTS inventory_corrections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    original_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    correction_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    reason TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(original_movement_id)
);
"""

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    supplier_name TEXT NOT NULL DEFAULT '',
    purchase_unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    sales_unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '課税仕入/課税売上 10%',
    lead_time_days INTEGER NOT NULL DEFAULT 7,
    safety_stock INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 0,
    min_order_quantity INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS business_partners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type TEXT NOT NULL CHECK (partner_type IN ('supplier', 'customer')),
    partner_name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(partner_type, partner_name)
);

CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    received_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price >= 0),
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price >= 0),
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    movement_type TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    movement_date TEXT NOT NULL,
    quantity_delta INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS freee_sync_queue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    payload_json TEXT NOT NULL,
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_type, source_id)
);

CREATE TABLE IF NOT EXISTS inventory_corrections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    correction_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(original_movement_id)
);
"""

# テナント分離・予測・証憑などのテーブルは A-3 以降で両 DDL に追記する。


def _dict_factory(cursor: sqlite3.Cursor, row: Sequence[Any]) -> dict[str, Any]:
    """SQLite の行を dict で返す（psycopg の dict_row と戻り値の形を揃える）。"""
    return {col[0]: row[idx] for idx, col in enumerate(cursor.description)}


class _Connection:
    """SQLite / psycopg を同じ API で扱う薄いラッパ。

    - execute(sql, params): SQL は常に '?' で書き、Postgres のときだけ '%s' へ変換する。
      params が None のときはパラメータ無しで実行する（psycopg が SQL 内の '%' を
      プレースホルダと誤認しないようにするため）。
    - 戻り値は dict を返すカーソル（fetchone()/fetchall()/lastrowid を持つ）。
    """

    def __init__(self, raw: Any, postgres: bool) -> None:
        self._raw = raw
        self.postgres = postgres

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        if self.postgres:
            sql = sql.replace("?", "%s")
            cur = self._raw.cursor()
            if params is None:
                cur.execute(sql)
            else:
                cur.execute(sql, params)
            return cur
        # SQLite: Connection.execute がそのまま dict 行カーソルを返す。
        if params is None:
            return self._raw.execute(sql)
        return self._raw.execute(sql, params)

    def executemany(self, sql: str, seq_of_params: Sequence[Sequence[Any]]) -> Any:
        if self.postgres:
            sql = sql.replace("?", "%s")
            cur = self._raw.cursor()
            cur.executemany(sql, list(seq_of_params))
            return cur
        return self._raw.executemany(sql, seq_of_params)

    def executescript(self, sql: str) -> None:
        # 複数文（スキーマDDL）をまとめて実行する。どちらの方言もパラメータ無し。
        if self.postgres:
            self._raw.cursor().execute(sql)
        else:
            self._raw.executescript(sql)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


@contextmanager
def get_conn(sqlite_path: str | os.PathLike[str] | None = None) -> Iterator[_Connection]:
    """トランザクション境界付きの接続を返す。

    正常終了で commit、例外で rollback、最後に必ず close。旧 app.get_conn と同じ契約。
    Postgres のときは sqlite_path は無視される。
    """
    if is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        raw = psycopg.connect(database_url(), row_factory=dict_row)
        conn = _Connection(raw, postgres=True)
    else:
        if sqlite_path is None:
            raise ValueError("sqlite_path is required when DATABASE_URL is not a Postgres URL")
        raw = sqlite3.connect(sqlite_path)
        raw.row_factory = _dict_factory
        raw.execute("PRAGMA foreign_keys = ON")
        conn = _Connection(raw, postgres=False)

    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def create_schema(conn: _Connection) -> None:
    """方言に応じたスキーマ DDL を流す（冪等: CREATE TABLE IF NOT EXISTS）。"""
    conn.executescript(POSTGRES_SCHEMA_SQL if conn.postgres else SQLITE_SCHEMA_SQL)


def insert_returning_id(conn: _Connection, sql: str, params: Sequence[Any]) -> int:
    """INSERT して採番された id を返す（lastrowid と RETURNING の差を吸収）。"""
    if conn.postgres:
        cur = conn.execute(sql.rstrip().rstrip(";") + " RETURNING id", params)
        return int(cur.fetchone()["id"])
    cur = conn.execute(sql, params)
    return int(cur.lastrowid)


def month_expr(conn: _Connection, column: str) -> str:
    """日付テキスト列から「月(1-12)」を取り出す SQL 断片を返す。

    SQLite は strftime、Postgres は EXTRACT。column は定数（列名）のみを渡すこと。
    """
    if conn.postgres:
        return f"CAST(EXTRACT(MONTH FROM {column}::date) AS INTEGER)"
    return f"CAST(strftime('%m', {column}) AS INTEGER)"


# FastAPI の例外ハンドラ登録用。使用中のバックエンドの IntegrityError を拾えるよう、
# 取り込めるものをまとめて公開する（psycopg 未インストールでも SQLite だけで動く）。
INTEGRITY_ERROR_TYPES: tuple[type[Exception], ...] = (sqlite3.IntegrityError,)
try:  # pragma: no cover - 実行環境に psycopg があるかどうかで分岐するだけ
    import psycopg as _psycopg

    INTEGRITY_ERROR_TYPES = (sqlite3.IntegrityError, _psycopg.IntegrityError)
except Exception:
    pass
