"""DB アクセス層（EVOLUTION_PLAN.md A-2: Neon 移行）。

このモジュールが「接続・スキーマDDL・SQL方言差の吸収」を一手に引き受ける。
業務ロジック(app.py)は方言を意識せず、常に '?' プレースホルダで SQL を書く。

DATABASE_URL による切替:
  - 未設定         → ローカル SQLite（開発・テストの既定）
  - postgresql://  → Neon などの Postgres（psycopg3）

方言差を吸収する箇所:
  - プレースホルダ : '?'(SQLite)        ⇄ '%s'(psycopg)          … _Connection.execute
  - 採番          : lastrowid(SQLite)   ⇄ INSERT ... RETURNING id … insert_returning_id
  - 月の抽出      : strftime(SQLite)    ⇄ EXTRACT(Postgres)       … month_expr
  - DDL          : AUTOINCREMENT/REAL  ⇄ IDENTITY/DOUBLE PRECISION … *_SCHEMA_SQL

設計境界（EVOLUTION_PLAN.md「データアクセス境界」）:
  DB への読み書き・スキーマ所有はサーバ側(Python)が唯一の主体。フロントは触らない。
"""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from typing import Any, Iterator, Sequence

# 業務ロジックの型注釈に使うエイリアス。実体は _Connection（SQLite/psycopg 両対応の薄いラッパ）。
Connection = Any


# ---------------------------------------------------------------------------
# バックエンド判定（DATABASE_URL を都度読むので、テストで環境変数を差し替えられる）
# ---------------------------------------------------------------------------
def database_url() -> str:
    return os.environ.get("DATABASE_URL", "").strip()


def is_postgres() -> bool:
    url = database_url()
    return url.startswith("postgres://") or url.startswith("postgresql://")


# ---------------------------------------------------------------------------
# スキーマ DDL（SQLite 版 / Postgres 版を併記）
# ---------------------------------------------------------------------------
# 2つの DDL は「同じ論理スキーマ」を表す。列を足すときは必ず両方を更新すること。
# 差分は方言のみ:
#   INTEGER PRIMARY KEY AUTOINCREMENT → INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
#   REAL                              → DOUBLE PRECISION
#   created_at/updated_at の TEXT      → TIMESTAMP（CURRENT_TIMESTAMP をそのまま代入できる）
#   PRAGMA foreign_keys = ON           → Postgres は常に FK 強制のため不要
SQLITE_SCHEMA_SQL = """
PRAGMA foreign_keys = ON;

-- A-3: テナント＆権限。全ドメインデータは organization_id で分離する。
CREATE TABLE IF NOT EXISTS organizations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 公開用は「1サインアップ=1組織」。user_id は Clerk のユーザID(sub)。
CREATE TABLE IF NOT EXISTS memberships (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    user_id TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'staff', 'viewer')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id);

-- A-3: 監査ログ（誰が・いつ・何を）。任意機能だが「見せる機能」として軽量導入。
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    actor_user_id TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL,
    target_type TEXT NOT NULL DEFAULT '',
    target_id TEXT NOT NULL DEFAULT '',
    detail_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_org ON audit_logs(organization_id, id);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    supplier_name TEXT NOT NULL DEFAULT '',
    purchase_unit_price REAL NOT NULL DEFAULT 0,
    sales_unit_price REAL NOT NULL DEFAULT 0,
    tax_rate REAL NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '課税仕入/課税売上 10%',
    lead_time_days INTEGER NOT NULL DEFAULT 7,
    safety_stock INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 0,
    min_order_quantity INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, sku)
);

CREATE TABLE IF NOT EXISTS business_partners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    partner_type TEXT NOT NULL CHECK (partner_type IN ('supplier', 'customer')),
    partner_name TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, partner_type, partner_name)
);

CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    received_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price REAL NOT NULL CHECK (unit_price >= 0),
    tax_rate REAL NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price REAL NOT NULL CHECK (unit_price >= 0),
    tax_rate REAL NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    movement_type TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    movement_date TEXT NOT NULL,
    quantity_delta INTEGER NOT NULL,
    unit_price REAL NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS freee_sync_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    payload_json TEXT NOT NULL,
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_type, source_id)
);

CREATE TABLE IF NOT EXISTS inventory_corrections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    original_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    correction_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    reason TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(original_movement_id)
);

-- A-4: 予測系。実績と同じ日次粒度。model_name で baseline/sarima/lightgbm を切替表示する。
CREATE TABLE IF NOT EXISTS forecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    target_date TEXT NOT NULL,
    model_name TEXT NOT NULL,
    predicted_quantity REAL NOT NULL DEFAULT 0,
    lower REAL NOT NULL DEFAULT 0,
    upper REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_forecasts_lookup
    ON forecasts(organization_id, product_id, model_name, target_date);

-- LightGBM の特徴量源（補助金フラグ・キャンペーン・カレンダー要因）。product_id NULL = 全体。
CREATE TABLE IF NOT EXISTS external_factors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    factor_date TEXT NOT NULL,
    factor_type TEXT NOT NULL,
    product_id INTEGER REFERENCES products(id),
    value REAL NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_external_factors
    ON external_factors(organization_id, factor_date);

-- 発注候補/月次発注リストを履歴保存。
CREATE TABLE IF NOT EXISTS order_candidates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    suggested_date TEXT NOT NULL,
    recommended_quantity INTEGER NOT NULL DEFAULT 0,
    basis TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- バックテストの精度指標（MAE/MAPE はモデル/期間単位で保持）。
CREATE TABLE IF NOT EXISTS model_evaluations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    model_name TEXT NOT NULL,
    period TEXT NOT NULL DEFAULT '',
    mae REAL NOT NULL DEFAULT 0,
    mape REAL NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS organizations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memberships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    user_id TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'staff', 'viewer')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    actor_user_id TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL,
    target_type TEXT NOT NULL DEFAULT '',
    target_id TEXT NOT NULL DEFAULT '',
    detail_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_org ON audit_logs(organization_id, id);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    sku TEXT NOT NULL,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    supplier_name TEXT NOT NULL DEFAULT '',
    purchase_unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    sales_unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '課税仕入/課税売上 10%',
    lead_time_days INTEGER NOT NULL DEFAULT 7,
    safety_stock INTEGER NOT NULL DEFAULT 0,
    reorder_point INTEGER NOT NULL DEFAULT 0,
    min_order_quantity INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, sku)
);

CREATE TABLE IF NOT EXISTS business_partners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    partner_type TEXT NOT NULL CHECK (partner_type IN ('supplier', 'customer')),
    partner_name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(organization_id, partner_type, partner_name)
);

CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    received_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price >= 0),
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    partner_name TEXT NOT NULL,
    invoice_no TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DOUBLE PRECISION NOT NULL CHECK (unit_price >= 0),
    tax_rate DOUBLE PRECISION NOT NULL DEFAULT 10,
    tax_category TEXT NOT NULL DEFAULT '',
    due_date TEXT NOT NULL DEFAULT '',
    external_accounting_status TEXT NOT NULL DEFAULT 'pending',
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    movement_type TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    movement_date TEXT NOT NULL,
    quantity_delta INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS freee_sync_queue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    payload_json TEXT NOT NULL,
    external_accounting_id TEXT NOT NULL DEFAULT '',
    sync_error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source_type, source_id)
);

CREATE TABLE IF NOT EXISTS inventory_corrections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    original_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    correction_movement_id INTEGER NOT NULL REFERENCES inventory_movements(id),
    reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(original_movement_id)
);

-- A-4: 予測系。実績と同じ日次粒度。model_name で baseline/sarima/lightgbm を切替表示する。
CREATE TABLE IF NOT EXISTS forecasts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    target_date TEXT NOT NULL,
    model_name TEXT NOT NULL,
    predicted_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    lower DOUBLE PRECISION NOT NULL DEFAULT 0,
    upper DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_forecasts_lookup
    ON forecasts(organization_id, product_id, model_name, target_date);

-- LightGBM の特徴量源（補助金フラグ・キャンペーン・カレンダー要因）。product_id NULL = 全体。
CREATE TABLE IF NOT EXISTS external_factors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    factor_date TEXT NOT NULL,
    factor_type TEXT NOT NULL,
    product_id INTEGER REFERENCES products(id),
    value DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_external_factors
    ON external_factors(organization_id, factor_date);

-- 発注候補/月次発注リストを履歴保存。
CREATE TABLE IF NOT EXISTS order_candidates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    product_id INTEGER NOT NULL REFERENCES products(id),
    suggested_date TEXT NOT NULL,
    recommended_quantity INTEGER NOT NULL DEFAULT 0,
    basis TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- バックテストの精度指標（MAE/MAPE はモデル/期間単位で保持）。
CREATE TABLE IF NOT EXISTS model_evaluations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    model_name TEXT NOT NULL,
    period TEXT NOT NULL DEFAULT '',
    mae DOUBLE PRECISION NOT NULL DEFAULT 0,
    mape DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""

# 証憑(vouchers)は A-5 で両 DDL に追記する。


def _dict_factory(cursor: sqlite3.Cursor, row: Sequence[Any]) -> dict[str, Any]:
    """SQLite の行を dict で返す（psycopg の dict_row と戻り値の形を揃える）。"""
    return {col[0]: row[idx] for idx, col in enumerate(cursor.description)}


def _to_pg_sql(sql: str) -> str:
    """'?' プレースホルダの SQL を psycopg(%s) 用に変換する（パラメータ有り専用）。

    リテラル % を先に %% へエスケープし、その後 '?' を '%s' に変える。順序を逆にすると
    生成した '%s' の % まで二重化されてしまうので必ずこの順序で行う。
    """
    return sql.replace("%", "%%").replace("?", "%s")


class _Connection:
    """SQLite / psycopg を同じ API で扱う薄いラッパ。

    - execute(sql, params): SQL は常に '?' で書き、Postgres のときだけ '%s' へ変換する。
      params が None のときはパラメータ無しで実行する（psycopg が SQL 内の '%' を
      プレースホルダと誤認しないようにするため）。
    - 戻り値は dict を返すカーソル（fetchone()/fetchall()/lastrowid を持つ）。
    """

    def __init__(self, raw: Any, postgres: bool) -> None:
        self._raw = raw
        self.postgres = postgres

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> Any:
        if self.postgres:
            cur = self._raw.cursor()
            if params is None:
                # パラメータ無し: psycopg は % を解釈しないので、LIKE 'x-%' や DDL 内の
                # リテラル % をそのまま送れる（'?' が無いので置換も実質 no-op）。
                cur.execute(sql.replace("?", "%s"))
            else:
                # パラメータ有り: psycopg は % をプレースホルダ扱いするため、SQL 内の
                # リテラル %（LIKE 'DEMO-HIST-S-%' など）を %% にエスケープしてから
                # '?' → '%s' に変換する。順序が重要（先にエスケープ→後でプレースホルダ）。
                cur.execute(_to_pg_sql(sql), params)
            return cur
        # SQLite: Connection.execute がそのまま dict 行カーソルを返す。
        if params is None:
            return self._raw.execute(sql)
        return self._raw.execute(sql, params)

    def executemany(self, sql: str, seq_of_params: Sequence[Sequence[Any]]) -> Any:
        if self.postgres:
            cur = self._raw.cursor()
            cur.executemany(_to_pg_sql(sql), list(seq_of_params))
            return cur
        return self._raw.executemany(sql, seq_of_params)

    def executescript(self, sql: str) -> None:
        # 複数文（スキーマDDL）をまとめて実行する。どちらの方言もパラメータ無し。
        if self.postgres:
            self._raw.cursor().execute(sql)
        else:
            self._raw.executescript(sql)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


@contextmanager
def get_conn(sqlite_path: str | os.PathLike[str] | None = None) -> Iterator[_Connection]:
    """トランザクション境界付きの接続を返す。

    正常終了で commit、例外で rollback、最後に必ず close。旧 app.get_conn と同じ契約。
    Postgres のときは sqlite_path は無視される。
    """
    if is_postgres():
        import psycopg
        from psycopg.rows import dict_row

        raw = psycopg.connect(database_url(), row_factory=dict_row)
        conn = _Connection(raw, postgres=True)
    else:
        if sqlite_path is None:
            raise ValueError("sqlite_path is required when DATABASE_URL is not a Postgres URL")
        raw = sqlite3.connect(sqlite_path)
        raw.row_factory = _dict_factory
        raw.execute("PRAGMA foreign_keys = ON")
        conn = _Connection(raw, postgres=False)

    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def create_schema(conn: _Connection) -> None:
    """方言に応じたスキーマ DDL を流す（冪等: CREATE TABLE IF NOT EXISTS）。"""
    conn.executescript(POSTGRES_SCHEMA_SQL if conn.postgres else SQLITE_SCHEMA_SQL)


# A-3 のドメインテーブル一式（テスト/テストブランチのリセット用。organizations 等も含む）。
# テストや「使い捨て/テスト用ブランチ」でのみ使う。本番では呼ばない。
DOMAIN_TABLES = (
    # A-4 予測系（products/organizations を参照するため先に DROP する）。
    "model_evaluations",
    "order_candidates",
    "external_factors",
    "forecasts",
    "audit_logs",
    "inventory_corrections",
    "freee_sync_queue",
    "inventory_movements",
    "sales",
    "purchases",
    "business_partners",
    "products",
    "memberships",
    "organizations",
)


def has_column(conn: _Connection, table: str, column: str) -> bool:
    """table に column が存在するか（方言差を吸収）。table/column は定数のみを渡すこと。"""
    if conn.postgres:
        row = conn.execute(
            """
            SELECT 1 FROM information_schema.columns
            WHERE table_name = ? AND column_name = ?
            """,
            (table, column),
        ).fetchone()
        return row is not None
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(row["name"] == column for row in rows)


def table_exists(conn: _Connection, table: str) -> bool:
    if conn.postgres:
        row = conn.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = ?",
            (table,),
        ).fetchone()
        return row is not None
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    ).fetchone()
    return row is not None


def is_legacy_schema(conn: _Connection) -> bool:
    """A-2 以前のスキーマ（products があるのに organization_id が無い）か。

    True のときに create_schema を流しても CREATE TABLE IF NOT EXISTS では
    既存テーブルに列を足せない。黙って壊さず assert_tenancy_ready で明示エラーにする。
    """
    return table_exists(conn, "products") and not has_column(conn, "products", "organization_id")


def assert_tenancy_ready(conn: _Connection) -> None:
    """テナント化スキーマ(A-3)が使える状態かを確認し、レガシーなら明示的に止める。

    データ破壊を避けるため、自動 DROP はしない。テストブランチ/使い捨てDBでは
    reset_domain_tables() でリセットしてから create_schema を流す運用にする。
    """
    if is_legacy_schema(conn):
        raise RuntimeError(
            "A-3 スキーマ変更: この DB は A-2 までの構造（organization_id 無し）です。"
            " デモデータは seed で再現できるため、テスト用ブランチ/使い捨てDBで"
            " db.reset_domain_tables() → 再 seed してください（本番Neonには向けないこと）。"
        )


def reset_domain_tables(conn: _Connection) -> None:
    """全ドメインテーブルを DROP する（テスト/テスト用ブランチ専用の破壊的操作）。

    本番DBに対しては絶対に呼ばないこと（EVOLUTION_PLAN.md「テストDBの分離」）。
    """
    if conn.postgres:
        for table in DOMAIN_TABLES:
            conn.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    else:
        for table in DOMAIN_TABLES:
            conn.execute(f"DROP TABLE IF EXISTS {table}")


def insert_returning_id(conn: _Connection, sql: str, params: Sequence[Any]) -> int:
    """INSERT して採番された id を返す（lastrowid と RETURNING の差を吸収）。"""
    if conn.postgres:
        cur = conn.execute(sql.rstrip().rstrip(";") + " RETURNING id", params)
        return int(cur.fetchone()["id"])
    cur = conn.execute(sql, params)
    return int(cur.lastrowid)


def month_expr(conn: _Connection, column: str) -> str:
    """日付テキスト列から「月(1-12)」を取り出す SQL 断片を返す。

    SQLite は strftime、Postgres は EXTRACT。column は定数（列名）のみを渡すこと。
    """
    if conn.postgres:
        return f"CAST(EXTRACT(MONTH FROM {column}::date) AS INTEGER)"
    return f"CAST(strftime('%m', {column}) AS INTEGER)"


# FastAPI の例外ハンドラ登録用。使用中のバックエンドの IntegrityError を拾えるよう、
# 取り込めるものをまとめて公開する（psycopg 未インストールでも SQLite だけで動く）。
INTEGRITY_ERROR_TYPES: tuple[type[Exception], ...] = (sqlite3.IntegrityError,)
try:  # pragma: no cover - 実行環境に psycopg があるかどうかで分岐するだけ
    import psycopg as _psycopg

    INTEGRITY_ERROR_TYPES = (sqlite3.IntegrityError, _psycopg.IntegrityError)
except Exception:
    pass
